name: Build release zip

on:
  release:
    types: [published]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip
        run: |
          cd custom_components/fn_nas
          zip -r ../fn_nas.zip .

      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} custom_components/fn_nas.zip --clobber
